import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const techRoles = [
    {
      title: "AI Engineer",
      description: "Design and implement cutting-edge artificial intelligence systems and neural networks.",
      category: "Technology",
      industry: "Artificial Intelligence",
      salaryMin: 120000,
      salaryMax: 250000,
      growthRate: 35,
      demandLevel: "Extreme",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["Python", "PyTorch", "LLMs", "Deep Learning"]),
      education: "Master's or PhD",
      experienceLevel: "Mid-Senior",
      workStyle: "Remote/Hybrid",
      futureOutlook: "Hyper-growth"
    },
    {
      title: "MLOps Engineer",
      description: "Scale and manage the deployment of machine learning models in production environments.",
      category: "Technology",
      industry: "AI Infrastructure",
      salaryMin: 115000,
      salaryMax: 230000,
      growthRate: 32,
      demandLevel: "Extreme",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["Python", "Kubernetes", "MLflow", "Cloud"]),
      education: "Bachelor's or Master's",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Essential for AI scale"
    },
    {
      title: "Software Engineer",
      description: "Build scalable and reliable software solutions for complex business problems.",
      category: "Technology",
      industry: "Software",
      salaryMin: 90000,
      salaryMax: 190000,
      growthRate: 15,
      demandLevel: "Very High",
      automationRisk: 0.2,
      requiredSkills: JSON.stringify(["Java", "Python", "System Design", "Agile"]),
      education: "Bachelor's Degree",
      experienceLevel: "All Levels",
      workStyle: "Any",
      futureOutlook: "Steady demand"
    },
    {
      title: "Data Scientist",
      description: "Extract actionable insights from complex datasets to drive business decisions.",
      category: "Technology",
      industry: "Data Science",
      salaryMin: 100000,
      salaryMax: 210000,
      growthRate: 22,
      demandLevel: "Very High",
      automationRisk: 0.15,
      requiredSkills: JSON.stringify(["Python", "SQL", "Statistics", "Machine Learning"]),
      education: "Master's or PhD",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Strong growth"
    },
    {
      title: "Cloud Architect",
      description: "Design and oversee an organization's cloud computing strategy and infrastructure.",
      category: "Technology",
      industry: "Cloud",
      salaryMin: 130000,
      salaryMax: 240000,
      growthRate: 20,
      demandLevel: "Extreme",
      automationRisk: 0.1,
      requiredSkills: JSON.stringify(["AWS/Azure", "Architecture", "Security", "Networking"]),
      education: "Bachelor's Degree",
      experienceLevel: "Senior",
      workStyle: "Hybrid",
      futureOutlook: "Cloud-first world"
    },
    {
      title: "Cybersecurity Analyst",
      description: "Protect organizational networks and data from cyber threats and breaches.",
      category: "Technology",
      industry: "Security",
      salaryMin: 90000,
      salaryMax: 180000,
      growthRate: 28,
      demandLevel: "Extreme",
      automationRisk: 0.1,
      requiredSkills: JSON.stringify(["Security Protocols", "Incident Response", "Network Security"]),
      education: "Bachelor's or Certs",
      experienceLevel: "All Levels",
      workStyle: "Hybrid",
      futureOutlook: "Critical need"
    },
    {
      title: "Full Stack Developer",
      description: "Develop both front-end and back-end components of web applications.",
      category: "Technology",
      industry: "Web Dev",
      salaryMin: 85000,
      salaryMax: 175000,
      growthRate: 14,
      demandLevel: "High",
      automationRisk: 0.2,
      requiredSkills: JSON.stringify(["React", "Node.js", "TypeScript", "Databases"]),
      education: "Bachelor's or Bootcamp",
      experienceLevel: "All Levels",
      workStyle: "Any",
      futureOutlook: "Versatile demand"
    },
    {
      title: "DevOps Engineer",
      description: "Optimize software development and delivery through automation and culture.",
      category: "Technology",
      industry: "Engineering Ops",
      salaryMin: 100000,
      salaryMax: 190000,
      growthRate: 18,
      demandLevel: "Very High",
      automationRisk: 0.1,
      requiredSkills: JSON.stringify(["CI/CD", "Docker", "Terraform", "Scripting"]),
      education: "Bachelor's Degree",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Ops modernization"
    },
    {
      title: "Data Engineer",
      description: "Build and maintain data pipelines and architectures for large-scale data processing.",
      category: "Technology",
      industry: "Data Engineering",
      salaryMin: 105000,
      salaryMax: 200000,
      growthRate: 25,
      demandLevel: "Very High",
      automationRisk: 0.12,
      requiredSkills: JSON.stringify(["Spark", "SQL", "Python", "Data Lakes"]),
      education: "Bachelor's Degree",
      experienceLevel: "All Levels",
      workStyle: "Hybrid",
      futureOutlook: "Foundation of AI"
    },
    {
      title: "Site Reliability Engineer (SRE)",
      description: "Apply engineering principles to ensure system reliability and performance at scale.",
      category: "Technology",
      industry: "Operations",
      salaryMin: 110000,
      salaryMax: 220000,
      growthRate: 17,
      demandLevel: "High",
      automationRisk: 0.08,
      requiredSkills: JSON.stringify(["SRE Principles", "Distributed Systems", "Incident Mgmt"]),
      education: "Bachelor's Degree",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Scale safety"
    },
    {
      title: "Blockchain Developer",
      description: "Develop decentralized applications and protocols using blockchain technology.",
      category: "Technology",
      industry: "FinTech/Web3",
      salaryMin: 110000,
      salaryMax: 250000,
      growthRate: 24,
      demandLevel: "Extreme",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["Solidity", "Rust", "Smart Contracts", "Cryptography"]),
      education: "Bachelor's Degree",
      experienceLevel: "Mid-Senior",
      workStyle: "Remote Preferred",
      futureOutlook: "Infrastructure growth"
    },
    {
      title: "Technical Product Manager",
      description: "Drive product strategy and execution with a deep technical understanding.",
      category: "Technology",
      industry: "Product",
      salaryMin: 120000,
      salaryMax: 210000,
      growthRate: 12,
      demandLevel: "High",
      automationRisk: 0.1,
      requiredSkills: JSON.stringify(["Strategy", "Agile", "API Knowledge", "Leadership"]),
      education: "CS + MBA preferred",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "AI product focus"
    },
    {
      title: "UI/UX Engineer",
      description: "Design and implement beautiful, user-centric digital interfaces.",
      category: "Technology",
      industry: "Design",
      salaryMin: 80000,
      salaryMax: 170000,
      growthRate: 13,
      demandLevel: "High",
      automationRisk: 0.15,
      requiredSkills: JSON.stringify(["Figma", "React", "Interaction Design", "Accessibility"]),
      education: "Design or CS Degree",
      experienceLevel: "All Levels",
      workStyle: "Any",
      futureOutlook: "User-first tech"
    },
    {
      title: "Mobile App Developer",
      description: "Build high-performance applications for iOS and Android platforms.",
      category: "Technology",
      industry: "Mobile",
      salaryMin: 90000,
      salaryMax: 185000,
      growthRate: 14,
      demandLevel: "High",
      automationRisk: 0.18,
      requiredSkills: JSON.stringify(["Swift", "Kotlin", "React Native", "Mobile UI"]),
      education: "Bachelor's Degree",
      experienceLevel: "All Levels",
      workStyle: "Any",
      futureOutlook: "Mobile-centric world"
    },
    {
      title: "Solutions Architect",
      description: "Design tailored technical solutions for enterprise client challenges.",
      category: "Technology",
      industry: "Consulting",
      salaryMin: 125000,
      salaryMax: 220000,
      growthRate: 16,
      demandLevel: "Very High",
      automationRisk: 0.08,
      requiredSkills: JSON.stringify(["Architecture", "Communication", "PoC", "Client Relations"]),
      education: "Senior Engineering Exp",
      experienceLevel: "Senior",
      workStyle: "Hybrid",
      futureOutlook: "Strategic tech advisor"
    },
    {
      title: "Ethical Hacker",
      description: "Find and help fix security vulnerabilities through authorized penetration testing.",
      category: "Technology",
      industry: "Cybersecurity",
      salaryMin: 100000,
      salaryMax: 210000,
      growthRate: 30,
      demandLevel: "Extreme",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["PenTesting", "Exploit Dev", "Network Security"]),
      education: "Bachelor's or OSCP",
      experienceLevel: "Mid-Senior",
      workStyle: "Remote/Hybrid",
      futureOutlook: "Essential security"
    },
    {
      title: "Computer Vision Engineer",
      description: "Develop algorithms that enable machines to understand visual data.",
      category: "Technology",
      industry: "AI/Vision",
      salaryMin: 130000,
      salaryMax: 260000,
      growthRate: 28,
      demandLevel: "Extreme",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["OpenCV", "Deep Learning", "C++", "Python"]),
      education: "Master's or PhD",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Autonomous/AR future"
    },
    {
      title: "NLP Engineer",
      description: "Build systems that can understand, interpret, and generate human language.",
      category: "Technology",
      industry: "AI/Language",
      salaryMin: 125000,
      salaryMax: 245000,
      growthRate: 33,
      demandLevel: "Extreme",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["Transformers", "PyTorch", "LLMs", "Linguistics"]),
      education: "Master's or PhD",
      experienceLevel: "Mid-Senior",
      workStyle: "Remote/Hybrid",
      futureOutlook: "Conversational AI era"
    },
    {
      title: "Autonomous Systems Engineer",
      description: "Engineer navigation and control for self-driving vehicles and robots.",
      category: "Technology",
      industry: "Robotics",
      salaryMin: 135000,
      salaryMax: 255000,
      growthRate: 27,
      demandLevel: "Very High",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["Control Theory", "SLAM", "C++", "Robotics"]),
      education: "Bachelor's or Master's",
      experienceLevel: "Mid-Senior",
      workStyle: "In-person/Hybrid",
      futureOutlook: "Autonomous world"
    },
    {
      title: "Cloud Security Engineer",
      description: "Secure multi-cloud environments through policy, encryption, and automation.",
      category: "Technology",
      industry: "Security/Cloud",
      salaryMin: 115000,
      salaryMax: 220000,
      growthRate: 29,
      demandLevel: "Extreme",
      automationRisk: 0.08,
      requiredSkills: JSON.stringify(["IAM", "Terraform", "Cloud Sec", "Compliance"]),
      education: "Bachelor's Degree",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Cloud-native protection"
    },
    {
      title: "Data Architect",
      description: "Create blueprints for an organization's high-level data strategy and structure.",
      category: "Technology",
      industry: "Data Architecture",
      salaryMin: 140000,
      salaryMax: 240000,
      growthRate: 19,
      demandLevel: "High",
      automationRisk: 0.1,
      requiredSkills: JSON.stringify(["Data Modeling", "Strategy", "Governance", "Database Design"]),
      education: "Senior Data Background",
      experienceLevel: "Senior",
      workStyle: "Hybrid",
      futureOutlook: "Strategic data lead"
    },
    {
      title: "Game Developer",
      description: "Create interactive entertainment and simulation experiences.",
      category: "Technology",
      industry: "Gaming",
      salaryMin: 75000,
      salaryMax: 170000,
      growthRate: 11,
      demandLevel: "High",
      automationRisk: 0.15,
      requiredSkills: JSON.stringify(["Unity/Unreal", "C++/C#", "3D Math", "Gameplay"]),
      education: "Bachelor's Degree",
      experienceLevel: "All Levels",
      workStyle: "Any",
      futureOutlook: "Entertainment growth"
    },
    {
      title: "AR/VR Developer",
      description: "Build immersive spatial computing experiences for headsets and mobile.",
      category: "Technology",
      industry: "Mixed Reality",
      salaryMin: 100000,
      salaryMax: 210000,
      growthRate: 25,
      demandLevel: "Extreme",
      automationRisk: 0.1,
      requiredSkills: JSON.stringify(["Unity/Unreal", "Spatial UI", "C#", "3D Graphics"]),
      education: "Bachelor's Degree",
      experienceLevel: "Mid-Senior",
      workStyle: "Hybrid",
      futureOutlook: "Next computing frontier"
    },
    {
      title: "Embedded Systems Engineer",
      description: "Develop firmware and software for hardware-constrained devices.",
      category: "Technology",
      industry: "IoT/Hardware",
      salaryMin: 90000,
      salaryMax: 175000,
      growthRate: 10,
      demandLevel: "High",
      automationRisk: 0.15,
      requiredSkills: JSON.stringify(["C/C++", "RTOS", "Microcontrollers", "Debugging"]),
      education: "EE or CS Degree",
      experienceLevel: "Mid-Senior",
      workStyle: "In-person/Hybrid",
      futureOutlook: "Smart devices"
    },
    {
      title: "Network Engineer",
      description: "Design and maintain high-speed global network infrastructure.",
      category: "Technology",
      industry: "Infrastructure",
      salaryMin: 80000,
      salaryMax: 160000,
      growthRate: 8,
      demandLevel: "High",
      automationRisk: 0.25,
      requiredSkills: JSON.stringify(["BGP/OSPF", "Networking", "SDN", "Security"]),
      education: "Bachelor's Degree",
      experienceLevel: "All Levels",
      workStyle: "Hybrid",
      futureOutlook: "SDN transformation"
    },
    {
      title: "Hardware Engineer",
      description: "Design and test physical electronic circuits and systems-on-chip.",
      category: "Technology",
      industry: "Hardware",
      salaryMin: 95000,
      salaryMax: 190000,
      growthRate: 9,
      demandLevel: "High",
      automationRisk: 0.15,
      requiredSkills: JSON.stringify(["PCB Design", "Verilog", "Circuits", "Manufacturing"]),
      education: "Electrical Engineering",
      experienceLevel: "Mid-Senior",
      workStyle: "In-person/Hybrid",
      futureOutlook: "Silicon innovation"
    },
    {
      title: "Information Security Manager",
      description: "Oversee an organization's overall security program and compliance.",
      category: "Technology",
      industry: "Security Mgmt",
      salaryMin: 110000,
      salaryMax: 200000,
      growthRate: 15,
      demandLevel: "Very High",
      automationRisk: 0.05,
      requiredSkills: JSON.stringify(["GRC", "Risk Mgmt", "Policies", "Leadership"]),
      education: "Senior Security Exp",
      experienceLevel: "Lead/Executive",
      workStyle: "Hybrid",
      futureOutlook: "Organizational safety"
    },
    {
      title: "QA Automation Engineer",
      description: "Engineer automated testing frameworks for software quality assurance.",
      category: "Technology",
      industry: "QA",
      salaryMin: 85000,
      salaryMax: 160000,
      growthRate: 10,
      demandLevel: "High",
      automationRisk: 0.3,
      requiredSkills: JSON.stringify(["Playwright", "Cypress", "Python", "Test Plans"]),
      education: "Bachelor's Degree",
      experienceLevel: "All Levels",
      workStyle: "Any",
      futureOutlook: "Automation standard"
    },
    {
      title: "QA Lead",
      description: "Manage quality strategy and lead teams of QA engineers.",
      category: "Technology",
      industry: "QA Mgmt",
      salaryMin: 110000,
      salaryMax: 185000,
      growthRate: 9,
      demandLevel: "High",
      automationRisk: 0.2,
      requiredSkills: JSON.stringify(["Strategy", "Leadership", "Risk-based Testing", "Mentoring"]),
      education: "Senior QA Exp",
      experienceLevel: "Lead/Manager",
      workStyle: "Hybrid",
      futureOutlook: "Quality governance"
    },
    {
      title: "Chief Technology Officer (CTO)",
      description: "Define long-term technical vision and scale engineering organizations.",
      category: "Technology",
      industry: "Executive",
      salaryMin: 180000,
      salaryMax: 450000,
      growthRate: 12,
      demandLevel: "Extreme",
      automationRisk: 0.01,
      requiredSkills: JSON.stringify(["Vision", "Leadership", "Recruiting", "Strategy"]),
      education: "Executive Exp",
      experienceLevel: "Executive",
      workStyle: "Hybrid/Office",
      futureOutlook: "Innovation lead"
    }
  ];

  console.log("Seeding master list of 30 tech roles...");

  for (const role of techRoles) {
    const slug = role.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    await prisma.career.upsert({
      where: { slug },
      update: role,
      create: { ...role, slug }
    });
  }

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
