const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const careers = [
  {
    title: "Software Engineer",
    slug: "software-engineer",
    description: "Develops, tests, and maintains software applications. Focuses on writing clean, efficient code and collaborating with cross-functional teams.",
    category: "Technology",
    industry: "Information Technology",
    salaryMin: 80000,
    salaryMax: 180000,
    growthRate: 22,
    demandLevel: "High",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["JavaScript", "TypeScript", "React", "Node.js", "System Design"]),
    education: "Bachelor's in CS",
    experienceLevel: "All Levels",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Excellent"
  },
  {
    title: "Data Scientist",
    slug: "data-scientist",
    description: "Analyzes complex data sets to help organizations make informed decisions using ML and statistics.",
    category: "Data",
    industry: "Tech/Finance",
    salaryMin: 95000,
    salaryMax: 195000,
    growthRate: 35,
    demandLevel: "Extreme",
    automationRisk: 0.05,
    requiredSkills: JSON.stringify(["Python", "SQL", "Machine Learning", "Statistics"]),
    education: "Master's or PhD",
    experienceLevel: "Mid to Senior",
    workStyle: "Hybrid",
    futureOutlook: "Rapid Growth"
  },
  {
    title: "AI Engineer",
    slug: "ai-engineer",
    description: "Specializes in developing intelligent systems, neural networks, and LLMs.",
    category: "Technology",
    industry: "Tech/AI",
    salaryMin: 120000,
    salaryMax: 250000,
    growthRate: 40,
    demandLevel: "Extreme",
    automationRisk: 0.02,
    requiredSkills: JSON.stringify(["PyTorch", "TensorFlow", "NLP", "LLMs"]),
    education: "Master's in AI/CS",
    experienceLevel: "Mid to Senior",
    workStyle: "Hybrid",
    futureOutlook: "Transformative"
  },
  {
    title: "Cybersecurity Analyst",
    slug: "cybersecurity-analyst",
    description: "Protects networks and systems from cyber attacks and data breaches.",
    category: "Security",
    industry: "IT/Government",
    salaryMin: 85000,
    salaryMax: 170000,
    growthRate: 33,
    demandLevel: "High",
    automationRisk: 0.08,
    requiredSkills: JSON.stringify(["Network Security", "Threat Detection", "Penetration Testing"]),
    education: "Bachelor's",
    experienceLevel: "All Levels",
    workStyle: "Hybrid",
    futureOutlook: "Critical"
  },
  {
    title: "UX Designer",
    slug: "ux-designer",
    description: "Designs intuitive interfaces and conducts research to improve user satisfaction.",
    category: "Design",
    industry: "Design/Creative",
    salaryMin: 70000,
    salaryMax: 155000,
    growthRate: 15,
    demandLevel: "High",
    automationRisk: 0.15,
    requiredSkills: JSON.stringify(["Figma", "User Research", "Prototyping"]),
    education: "Bachelor's",
    experienceLevel: "All Levels",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Steady"
  },
  {
    title: "Cloud Architect",
    slug: "cloud-architect",
    description: "Designs and manages cloud infrastructure and migration strategies.",
    category: "Technology",
    industry: "IT",
    salaryMin: 110000,
    salaryMax: 210000,
    growthRate: 25,
    demandLevel: "High",
    automationRisk: 0.05,
    requiredSkills: JSON.stringify(["AWS", "Azure", "Terraform", "Docker"]),
    education: "Bachelor's",
    experienceLevel: "Senior",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Strong"
  },
  {
    title: "DevOps Engineer",
    slug: "devops-engineer",
    description: "Automates software delivery and manages infrastructure stability.",
    category: "Technology",
    industry: "IT",
    salaryMin: 90000,
    salaryMax: 185000,
    growthRate: 28,
    demandLevel: "High",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["CI/CD", "Kubernetes", "Ansible", "Linux"]),
    education: "Bachelor's",
    experienceLevel: "Mid to Senior",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Excellent"
  },
  {
    title: "Full Stack Developer",
    slug: "full-stack-developer",
    description: "Builds both front-end and back-end components of web applications.",
    category: "Technology",
    industry: "Tech",
    salaryMin: 85000,
    salaryMax: 175000,
    growthRate: 20,
    demandLevel: "High",
    automationRisk: 0.12,
    requiredSkills: JSON.stringify(["React", "Node.js", "PostgreSQL", "Next.js"]),
    education: "Bachelor's or Bootcamp",
    experienceLevel: "All Levels",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Very Strong"
  },
  {
    title: "Blockchain Developer",
    slug: "blockchain-developer",
    description: "Develops decentralized applications and smart contracts.",
    category: "Technology",
    industry: "Finance/Tech",
    salaryMin: 100000,
    salaryMax: 220000,
    growthRate: 30,
    demandLevel: "Medium",
    automationRisk: 0.05,
    requiredSkills: JSON.stringify(["Solidity", "Rust", "Web3.js", "Cryptography"]),
    education: "Bachelor's",
    experienceLevel: "Mid to Senior",
    workStyle: "Remote",
    futureOutlook: "Emerging"
  },
  {
    title: "Product Manager",
    slug: "product-manager",
    description: "Leads the strategy and roadmap for products, bridging business and tech.",
    category: "Management",
    industry: "Business/Tech",
    salaryMin: 90000,
    salaryMax: 200000,
    growthRate: 12,
    demandLevel: "High",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["Strategy", "Roadmapping", "Agile", "Analytics"]),
    education: "Bachelor's/MBA",
    experienceLevel: "Mid to Senior",
    workStyle: "Hybrid",
    futureOutlook: "Solid"
  },
  {
    title: "Mobile App Developer",
    slug: "mobile-app-developer",
    description: "Creates applications for iOS and Android platforms.",
    category: "Technology",
    industry: "Tech",
    salaryMin: 80000,
    salaryMax: 165000,
    growthRate: 18,
    demandLevel: "High",
    automationRisk: 0.15,
    requiredSkills: JSON.stringify(["Swift", "Kotlin", "React Native", "Flutter"]),
    education: "Bachelor's",
    experienceLevel: "All Levels",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Strong"
  },
  {
    title: "QA Automation Engineer",
    slug: "qa-automation-engineer",
    description: "Develops automated tests to ensure software quality and reliability.",
    category: "Technology",
    industry: "IT",
    salaryMin: 75000,
    salaryMax: 150000,
    growthRate: 15,
    demandLevel: "Medium",
    automationRisk: 0.2,
    requiredSkills: JSON.stringify(["Selenium", "Playwright", "Python", "CI/CD"]),
    education: "Bachelor's",
    experienceLevel: "All Levels",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Steady"
  },
  {
    title: "Solutions Architect",
    slug: "solutions-architect",
    description: "Designs end-to-end technical solutions for specific business problems.",
    category: "Technology",
    industry: "IT/Consulting",
    salaryMin: 120000,
    salaryMax: 220000,
    growthRate: 18,
    demandLevel: "High",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["Architecture Design", "Stakeholder Management", "Cloud"]),
    education: "Bachelor's",
    experienceLevel: "Senior",
    workStyle: "Hybrid",
    futureOutlook: "Strong"
  },
  {
    title: "Ethical Hacker",
    slug: "ethical-hacker",
    description: "Legally penetrates systems to find and fix security vulnerabilities.",
    category: "Security",
    industry: "IT/Security",
    salaryMin: 90000,
    salaryMax: 180000,
    growthRate: 35,
    demandLevel: "High",
    automationRisk: 0.05,
    requiredSkills: JSON.stringify(["PenTesting", "Network Security", "Linux", "Python"]),
    education: "Bachelor's",
    experienceLevel: "Mid to Senior",
    workStyle: "Hybrid",
    futureOutlook: "Critical"
  },
  {
    title: "Network Engineer",
    slug: "network-engineer",
    description: "Designs and maintains the physical and virtual networks of an organization.",
    category: "Technology",
    industry: "IT",
    salaryMin: 70000,
    salaryMax: 150000,
    growthRate: 8,
    demandLevel: "Medium",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["Cisco", "Routing/Switching", "Firewalls", "VPN"]),
    education: "Bachelor's",
    experienceLevel: "All Levels",
    workStyle: "On-site/Hybrid",
    futureOutlook: "Steady"
  },
  {
    title: "Computer Vision Engineer",
    slug: "computer-vision-engineer",
    description: "Develops algorithms that allow computers to understand images and video.",
    category: "Technology",
    industry: "AI/Auto",
    salaryMin: 110000,
    salaryMax: 230000,
    growthRate: 38,
    demandLevel: "High",
    automationRisk: 0.05,
    requiredSkills: JSON.stringify(["OpenCV", "Deep Learning", "C++", "Python"]),
    education: "Master's/PhD",
    experienceLevel: "Mid to Senior",
    workStyle: "Hybrid",
    futureOutlook: "High Growth"
  },
  {
    title: "NLP Engineer",
    slug: "nlp-engineer",
    description: "Specializes in allowing machines to understand and process human language.",
    category: "Technology",
    industry: "AI/Tech",
    salaryMin: 115000,
    salaryMax: 240000,
    growthRate: 42,
    demandLevel: "Extreme",
    automationRisk: 0.03,
    requiredSkills: JSON.stringify(["Transformers", "PyTorch", "LLMs", "Linguistics"]),
    education: "Master's/PhD",
    experienceLevel: "Mid to Senior",
    workStyle: "Hybrid/Remote",
    futureOutlook: "Exceptional"
  },
  {
    title: "Embedded Systems Engineer",
    slug: "embedded-systems-engineer",
    description: "Writes software for specialized hardware and microcontrollers.",
    category: "Technology",
    industry: "Manufacturing/Auto",
    salaryMin: 85000,
    salaryMax: 170000,
    growthRate: 12,
    demandLevel: "Medium",
    automationRisk: 0.08,
    requiredSkills: JSON.stringify(["C/C++", "RTOS", "Microcontrollers", "Hardware"]),
    education: "Bachelor's",
    experienceLevel: "Mid to Senior",
    workStyle: "On-site/Hybrid",
    futureOutlook: "Steady"
  },
  {
    title: "Game Developer",
    slug: "game-developer",
    description: "Designs and builds interactive video games for various platforms.",
    category: "Creative",
    industry: "Entertainment",
    salaryMin: 70000,
    salaryMax: 160000,
    growthRate: 15,
    demandLevel: "Medium",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["Unity", "Unreal Engine", "C#", "C++"]),
    education: "Bachelor's",
    experienceLevel: "All Levels",
    workStyle: "Hybrid/On-site",
    futureOutlook: "Competitive"
  },
  {
    title: "AR/VR Developer",
    slug: "ar-vr-developer",
    description: "Creates immersive experiences for augmented and virtual reality.",
    category: "Technology",
    industry: "Tech/Edu",
    salaryMin: 90000,
    salaryMax: 180000,
    growthRate: 30,
    demandLevel: "Medium",
    automationRisk: 0.05,
    requiredSkills: JSON.stringify(["Unity", "Spatial Computing", "C#", "3D Modeling"]),
    education: "Bachelor's",
    experienceLevel: "Mid to Senior",
    workStyle: "Remote/Hybrid",
    futureOutlook: "Emerging"
  },
  {
    title: "Hardware Engineer",
    slug: "hardware-engineer",
    description: "Designs physical components like circuit boards and processors.",
    category: "Technology",
    industry: "Manufacturing",
    salaryMin: 85000,
    salaryMax: 175000,
    growthRate: 10,
    demandLevel: "Medium",
    automationRisk: 0.1,
    requiredSkills: JSON.stringify(["PCB Design", "Digital Logic", "VHDL/Verilog"]),
    education: "Bachelor's in EE",
    experienceLevel: "Mid to Senior",
    workStyle: "On-site",
    futureOutlook: "Steady"
  },
  {
    title: "Chief Technology Officer",
    slug: "cto",
    description: "High-level executive responsible for the entire technical vision of a company.",
    category: "Executive",
    industry: "Tech/Business",
    salaryMin: 150000,
    salaryMax: 450000,
    growthRate: 8,
    demandLevel: "Medium",
    automationRisk: 0.02,
    requiredSkills: JSON.stringify(["Leadership", "Strategy", "Organizational Design"]),
    education: "Bachelor's/MBA",
    experienceLevel: "Executive",
    workStyle: "Hybrid/On-site",
    futureOutlook: "Strategic"
  }
];

async function main() {
  console.log('Restoring Career Compendium...');
  for (const career of careers) {
    await prisma.career.upsert({
      where: { slug: career.slug },
      update: career,
      create: career,
    });
  }
  console.log('Restoration Finished: 22 Critical Roles Active.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
